apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: advent
    aadpodidbinding: advent-msi-example
  name: advent
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: advent
        aadpodidbinding: advent-msi-example
    spec:
      containers:
      - name: advent
        image: "docker.io/ned1313/aks-id-app:0.6"
        imagePullPolicy: Always
        ports: 
          - name: http
            containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: advent-svc
spec:
  selector:
    app: advent
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  type: LoadBalancer
